### ISSUE TITLE
Not working if subscription is done before first element is rendered

### ISSUE THREAD

**Issue by laszlokorte** [CyclicMaterials/cycle-hammer-driver#1]
If the subscription to `DOM.select('.my-element').events('pan')` is done before `.my-element` is rendered the first time, the listener is not bound correctly.

I assume this check is there to handle that case:
https://github.com/CyclicMaterials/cycle-hammer-driver/blob/develop/src/hammerDriver.js#L14

But it is not working because `element` is an array ie is always true, even if empty. According to @TylorS that is the expected behavior.

So I think that condition should be changed to `(!element.length)` for a quick fix.

The _real_ problem seems to be here: https://github.com/CyclicMaterials/cycle-hammer-driver/blob/develop/src/fromEvent.js#L49-L51 that the event listener is cached by selector name.
If the DOM node that corresponds to the selector changes (in my specific case from not existing to existing) the listener is not added to the new element.
I suspect that also causes problem if an element is recreated for any reasons (remove from the vdom, then later added again but as newly created element).

Currently a application side work around for this issue is:

```
const resize$ = handle.observable.skip(1).take(1).flatMap(() => panStart$
    .flatMap(() =>
      panMove$
      .map((evt) => evt.srcEvent.pageX / evt.target.parentNode.clientWidth)
      .takeUntil(panEnd$)
    )
  ).share();
```

**Comment by Frikki** [comment]
Thanks for reporting your findings. I don’t have much time at hand at the moment, so if you feel like making a PR with a fix, it’ll be much appreciated.

**Comment by laszlokorte** [comment]
I just noticed a few other issues with the hammer driver: If I understand it correctly `DOM.select('.foo').events('panstart')` only creates the hammer object the first time a `.foo` element is created and then caches it. This make it not detecting gestures on other `.foo` elements that are created later.
Additionally event propagation/isolation seem to not work as I would expect I can not figure out how to prevent a gesture from being detected by a parent component if it already has been detected and handles by a child component.

I will try to come up with a way to make the behavior consistent with the recent event delegation changes in cycle-dom. If I get it working I will send you a PR.

**Comment by Frikki** [comment]
Okay. I’m still too busy to look into this at the moment. You findings are very valuable. thanks.

**Comment by laszlokorte** [comment]
Currently I do not have time to investigate this further. For now I ended up building my own pinch and pan detection by combining raw `touchmove` `touchstart` and `mousemove` event streams in a few lines of code. Spending some hours looking into the hammerjs source code I actually think it could be simpler to build a some rx based gesture detection than wrapping hammerjs and making it work with cyclejs.

**Comment by Frikki** [comment]
Sounds good. Initially, it was André Staltz who encouraged me to build the driver, because he believed it would attract people to use Cycle.js. Anyway, please tell me about how I can see your progress.

**Comment by laszlokorte** [comment]
This is my current implementation for recognizing Pinch and and Pan events:

https://gist.github.com/laszlokorte/c415cf037726683c3137

It's still work in progress but the important part is the `toucheIds()` function which keeps track of only those touches that happen inside the `isolate`d  component.
I think other gestures like rotation can be added easily as well.

`globalEvents` is an object with an `events` method that returns an Observable for the given DOM event bound to the document
`rootElement` is the element selected by the DOM driver. Eg `DOM.select('.my-canvas')`
`svgEventPosition` is a function `({x,y}, el) -> ({x,y}` that converts the event's position into a custom coordinate system. `el` is the `ownerTarget` of the event.

**Comment by Frikki** [comment]
:+1:
